version: '3.4'
services:
  mssql:
    container_name: mssql-db
    hostname: mssql-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_SA_PASSWORD: 'Admin@123'
      MSSQL_DATA_DIR: /var/opt/mssql/data
      MSSQL_PID: 'Developer' 
      MSSQL_TCP_PORT: 1433 
    networks:
      - backend
    ports: 
      - "1455:1433"
    volumes:
      - ./container/sql/data:/var/opt/mssql/data
      - ./container/sql/log:/var/opt/mssql/log
      - ./container/sql/secrets:/var/opt/mssql/secrets
  redis:
    container_name: redis
    image: redis:latest
    networks:
      - backend
    ports:
      - "6379:6379"
  rabbitmq:
    container_name: rabbitmq
    hostname: rabbitmq
    image: rabbitmq:management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: 'user'
      RABBITMQ_DEFAULT_PASS: 'password'
    ports:
      - "5672:5672"
      - "15672:15672" 
    volumes:
        - ./container/rabbitmq/data/:/var/lib/rabbitmq/
        - ./container/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - rabbitmq_go_net
  email:
    container_name: email
    hostname: email
    image: sj26/mailcatcher
    ports:
      - "1025:1025"
      - "1080:1080"
  socialnet.auth:
    container_name: socialnet.auth
    hostname: socialnet.auth
    image: socialnet.auth:latest
    networks: 
      - backend
    ports:
      - "44391:443"
      - "44390:80"
    environment:
    - ASPNETCORE_URLS=https://+;http://+
    - ASPNETCORE_HTTPS_PORTS=8081
    - ASPNETCORE_Kestrel__Certificates__Default__Password=Pass@1234
    - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/certificates/aspnetapp.pfx

networks:
  rabbitmq_go_net:
    driver: bridge
  backend:
    driver: bridge
    
