CREATE TABLE [dbo].[Boards]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 
    [Title] NVARCHAR(100) NOT NULL, 
    [OwnerId] UNIQUEIDENTIFIER NOT NULL, 
    [IsDeleted] BIT NOT NULL DEFAULT 0, 
    [IsGeneral] BIT NOT NULL DEFAULT 0
)
